### ISSUE TITLE
BUG: Dynamic new in Where() causes NRE

### ISSUE THREAD

**Issue by xumix** [StefH/System.Linq.Dynamic.Core#130] opened 2017-12-19 16:18 UTC
``` c#
 var keys = context.Model.FindEntityType(type).FindPrimaryKey().Properties;
            var properties = keys.Select(p => new DynamicProperty(p.PropertyInfo.Name, p.PropertyInfo.PropertyType)).ToList();
            var keyType = DynamicClassFactory.CreateType(properties, false);
           
            var dbSet = context.Set<SomeEntity>();
            
            var keyVals = (IList)ReflectionHelper.CreateGenericInstance(typeof(List<>), new[] { keyType });

            foreach (var obj in data)
            {
                var keyVal = Activator.CreateInstance(keyType);
                foreach (var key in keys)
                {
                    keyType.GetProperty(key.PropertyInfo.Name).SetValue(keyVal, key.PropertyInfo.GetValue(obj));
                }

                keyVals.Add(keyVal);
            }
            
            Func<string> getNew = () =>
            {
                var res = keys.Select(key => "it." + key.Name + " as " + key.Name).ToList();
                return "new(" + res.ToString(",") + ")";
            };

            Func<string> getContains = () => ".Contains(" + getNew() + ")";

            var existing = dbSet.Where("@0" + getContains(), keyVals)
                .Select(getNew());
```
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at System.Linq.Dynamic.Core.ExpressionParser.CreateNewExpression(List`1 properties, List`1 expressions, Type newType) in C:\Projects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\ExpressionParser.cs:line 1491

```

**Comment by StefH** [comment] 2017-12-24 08:30
I'm not able to reproduce this issue. Can you please write working demo code based on https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src-console/ConsoleAppEF2.0/Program.cs ?

**Comment by xumix** [comment] 2018-01-09 15:18
@StefH here we go:
```
object CreateGenericInstance(Type type, Type[] types, params dynamic[] ctorParams)
        {
            var genType = type.MakeGenericType(types);

            var ct = genType.GetConstructors().First();
            return ct.Invoke(ctorParams);
        }


var keys = context.Model.FindEntityType(typeof(Car)).FindPrimaryKey().Properties;
            var properties = keys.Select(p => new DynamicProperty(p.PropertyInfo.Name, p.PropertyInfo.PropertyType)).ToList();
            var keyType = DynamicClassFactory.CreateType(properties, false);
           
            var dbSet = context.Set<Car>();
            
            var keyVals = (IList)CreateGenericInstance(typeof(List<>), new[] { keyType });

            foreach (var obj in context.Cars.ToArray())
            {
                var keyVal = Activator.CreateInstance(keyType);
                foreach (var key in keys)
                {
                    keyType.GetProperty(key.PropertyInfo.Name).SetValue(keyVal, key.PropertyInfo.GetValue(obj));
                }

                keyVals.Add(keyVal);
            }
            
            Func<string> getNew = () =>
            {
                var res = keys.Select(key => "it." + key.Name + " as " + key.Name).ToList();
                return "new(" + string.Join(",", res) + ")";
            };

            Func<string> getContains = () => ".Contains(" + getNew() + ")";

            var existing = dbSet.Where("@0" + getContains(), keyVals).Select(getNew()).ToDynamicList();


```

**Comment by StefH** [comment] 2018-01-09 17:42
Thanks.

**Comment by StefH** [comment] 2018-01-09 20:31
New NuGet will be released soon.

**Closed** 2018-01-09 20:31 UTC

**Comment by xumix** [comment] 2018-01-09 21:03
Thanks!
