### ISSUE TITLE
Issue: Using escaped strings is not working correctly

### ISSUE THREAD

**Issue by hypetsch** [StefH/System.Linq.Dynamic.Core#163] opened 2018-05-04 07:53 UTC
In issue #65 some issues regarding the usage of escaped strings have been fixed. I am currently facing another issue in combination with escaped characters (backslashes and quotation marks). 
`TextParser.cs` seems to not handle those scenarios correctly.
I have been able to reproduce the issue in unit tests:

``` c#
[Fact]
public void ParseLambda_StringLiteral_Backslash()
{
    string expectedLeftValue = "Property1.IndexOf(\"\\\")";
    string expectedRightValue = "0";
    var expression = DynamicExpressionParser.ParseLambda(
        new[] { Expression.Parameter(typeof(string), "Property1") },
        typeof(Boolean),
        string.Format("{0} >= {1}", expectedLeftValue, expectedRightValue));

    string leftValue = ((BinaryExpression)expression.Body).Left.ToString();
    string rightValue = ((BinaryExpression)expression.Body).Right.ToString();
    Assert.Equal(typeof(Boolean), expression.Body.Type);
    Assert.Equal(expectedLeftValue, leftValue);
    Assert.Equal(expectedRightValue, rightValue);
}

[Fact]
public void ParseLambda_StringLiteral_QuotationMark()
{
    string expectedLeftValue = "Property1.IndexOf(\"\\\"\")";
    string expectedRightValue = "0";
    var expression = DynamicExpressionParser.ParseLambda(
        new[] { Expression.Parameter(typeof(string), "Property1") },
        typeof(Boolean),
        string.Format("{0} >= {1}", expectedLeftValue, expectedRightValue));

    string leftValue = ((BinaryExpression)expression.Body).Left.ToString();
    string rightValue = ((BinaryExpression)expression.Body).Right.ToString();
    Assert.Equal(typeof(Boolean), expression.Body.Type);
    Assert.Equal(expectedLeftValue, leftValue);
    Assert.Equal(expectedRightValue, rightValue);
}
```

I think the issue is that the current implementation assumes that it is always a full string (starting and ending with an escaped quotation mark) and not only a single escaped character.

**Edit:** Updated unit tests code

**Comment by SolidWhiteSven** [comment] 2019-04-16 09:36
Hey, I got this issue again but only for backslashes, when switching from the NuGet package
```Text
wilx.System.Linq.Dynamic.Core 
```
(https://www.nuget.org/packages/wilx.System.Linq.Dynamic.Core/)
to
```Text
System.Linq.Dynamic.Core
```
I think the later one should be used?

Error:
```Text
System.Linq.Dynamic.Core.Exceptions.ParseException: 'Unterminated string literal'
```

Console app code to reproduce:
```CSharp
static void Main(string[] args)
{
    var strings = new[] { "test \\ string" }.AsQueryable();

    var count = strings.Count("ToString().Contains('\\')");
    //var count = strings.Count(s => s.ToString().Contains('\\'));

    Console.WriteLine("Elements found (should be 1): " + count);
    Console.ReadKey();
}
```

**Comment by StefH** [comment] 2019-04-16 12:36
As a workaround you can use:
`var count = strings.Count("Contains(@0)", "\\");`

**Comment by SolidWhiteSven** [comment] 2019-04-16 12:53
Thank you for the answer, this worked for me in the given example. At a different point we use an input string to filter out elements, so it would be quite complicated to get it to work that way, having multiple inputs for each argument in the string predicate, as well as that filter string containing the arguments.

Is there a plan to fix this in the future?

Thank you for your help!

**Comment by StefH** [comment] 2019-04-17 05:29
I see your point, it seems that the parsing code in this library is different regarding escaping. I'll take a look if I can find and fix the logic.

**Comment by StefH** [comment] 2019-04-17 16:08
@hypetsch and @SolidWhiteSven 
I've changed the code, please try version 1.0.13-ci-11242 from MyGet.

https://www.myget.org/feed/system-linq-dynamic-core/package/nuget/System.Linq.Dynamic.Core

**Comment by SolidWhiteSven** [comment] 2019-04-23 08:11
Hey @StefH, I've added the prerelease package with version 1.0.13-ci-11244 to the solution, but sadly I still get the 'Unterminated string literal' exception. I also thought the changes were only in the mentioned 11242 version, but that one also throws the error for this code:
```CSharp
using System;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var strings = new[] { "test \\ string" }.AsQueryable();

            var count = strings.Count("Contains('\\')");

            Console.WriteLine("Elements found (should be 1): " + count);
            Console.ReadKey();
        }
    }
}
```

**Comment by StefH** [comment] 2019-04-23 09:18
You are correct, this test does not work. I've to double check the code again...

**Comment by StefH** [comment] 2019-04-27 14:59
@SolidWhiteSven 
Can you try 1.0.13-ci-11260 ?

**Comment by SolidWhiteSven** [comment] 2019-04-29 06:35
@StefH Works like a charm, thank you!

**Comment by StefH** [comment] 2019-04-29 07:49
@hypetsch Can you also do some tests please?

**Comment by hypetsch** [comment] 2019-04-30 07:27
@StefH, thanks for sour work. Just did a quick test: the test case `ParseLambda_StringLiteral_Backslash()` I added in the first comment still fails with a `ParseException` ('Unterminated string literal'). Think the test itself should be ok?

**Comment by StefH** [comment] 2019-04-30 07:35
@hypetsch
Yes I noticed that also, so I changed the unit-test to be :
``` c#
string expectedLeftValue = "Property1.IndexOf(\"\\\\\")";
```

Which means (to my knowledge):

- `\"` --> escape the double quote (start)
- `\\\\` --> define a backslash : because the backslash is inside the double quotes, you need to escape it twice. If you just use `\\`, this will be translated to `\` which is not valid because this is an escape character (https://devblogs.microsoft.com/csharpfaq/what-character-escape-sequences-are-available/) So we need to double escape the backslash
- `\"` --> escape the double quote (end)

**Comment by hypetsch** [comment] 2019-04-30 08:00
Sorry, think you are right.
Some other tests I did meanwhile worked well. Thanks.

**Comment by StefH** [comment] 2019-04-30 08:12
Thank you both for your help !

I will close this issue and merge the PR; in some time, I'll create a new official NuGet.

**Closed by StefH** 2019-04-30 08:12 UTC
