### ISSUE TITLE
Question: OrderBy does not work with navigation properties

### ISSUE THREAD

**Issue by vonaerich** [StefH/System.Linq.Dynamic.Core#101] opened 2017-08-19 18:55 UTC
I was trying to do something like 
```
list.OrderBy("Parent.Code asc");
```
but it doesn't seem to work.
I'm pretty sure it works before (dotnet core)
Suggestions?

**Comment by statler** [comment] 2017-08-28 10:23
Its not just orderby - where does not work either, in fact no override of where or orderby seem to take a string

**Comment by StefH** [comment] 2017-08-28 10:51
Strange, unit-test code just looks fine : https://github.com/StefH/System.Linq.Dynamic.Core/blob/40d3b73ffadcb2a6e927767a9b9f7cdd49641663/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L17

Maybe you miss an **using** statement?

**Comment by vonaerich** [comment] 2017-08-30 06:04
@StefH, I think I stumbled upon a weird naming issue. It's not working when I used "Parent" as my property name but when I changed the property name into something else, it is working as expected. 

@statler, yea maybe you're missing a using statement. Both orderby and where works for me.

**Comment by StefH** [comment] 2017-08-31 11:02
@statler Can you confirm?

**Comment by belmirp** [comment] 2017-09-02 09:34
I have the same issue. I am using DataTables and it is not working when there is a navigation property. This is the screenshot of the error:

![orderbyissue](https://user-images.githubusercontent.com/12861786/29994553-c6310b68-8fda-11e7-8ad8-6bcd7e98d432.jpg)

There is using statement (using System.Linq.Dynamic.Core;) and the value of the sortOrder variable is "Project.PriorityC".

**Comment by StefH** [comment] 2017-09-02 19:51
@belmirp can you copy that full expression from that debug window ?

**Comment by belmirp** [comment] 2017-09-02 21:00
{value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[SIMS.Models.Stakeholder]).Where(w => IIF(((value(SIMS.Controllers.StakeholderController+<>c__DisplayClass3_0).pid != null) AndAlso (value(SIMS.Controllers.StakeholderController+<>c__DisplayClass3_0).pid != Convert(0))), value(SIMS.Controllers.StakeholderController+<>c__DisplayClass3_0).sid.Contains(w.StakeholderId), (Convert(w.StakeholderId) != null))).Select(s => new IndexViewModel() {StakeholderId = s.StakeholderId, Name = s.Name, Type = s.Type, TypeS = s.TypeS, Projects = value(SIMS.Controllers.StakeholderController)._context.StakeholderProjects.Count(c => (c.StakeholderId == s.StakeholderId)), Members = value(SIMS.Controllers.StakeholderController)._context.StakeholderMembers.Count(c => (c.StakeholderId == s.StakeholderId)), Project = IIF(((value(SIMS.Controllers.StakeholderController+<>c__DisplayClass3_0).pid != null) AndAlso (value(SIMS.Controllers.StakeholderController+<>c__DisplayClass3_0).pid != Convert(0))), value(SIMS.Controllers.StakeholderController)._context.StakeholderProjects.Where(w => ((w.StakeholderId == s.StakeholderId) AndAlso (Convert(w.ProjectId) == value(SIMS.Controllers.StakeholderController+<>c__DisplayClass3_0).pid))).Include(i => i.AttitudeScale).Include(i => i.AttitudeScale.Labels).FirstOrDefault(), new StakeholderProject() {PriorityC = 0, PriorityA = 0}), HasPhoto = ((s.Photo != null) AndAlso (ArrayLength(s.Photo) > 0))}).OrderBy(Param_0 => Param_0.Project.PriorityC)}

**Comment by StefH** [comment] 2017-09-03 07:28
I've created a example project in NETCore 1.1 to reproduce this issue.
https://github.com/StefH/System.Linq.Dynamic.Core/tree/master/src-console/Test.NETCoreApp.EntityFrameworkCore

But this just works fine.

Can you please take a look at the example, and tell me what differs with your code?

Also, if possible, create a same example project with your data and entities.

**Comment by belmirp** [comment] 2017-09-03 10:03
I think I have found where is the problem or difference. 

I am trying to apply OrderBy on Project property (i.e. "Project.PriorityC") in this IndexViewModel:

    public class IndexViewModel
    {
        [Key]
        public int StakeholderId { get; set; }

        public string Name { get; set; }

        public StakeholderProject Project { get; set; }

        public Gender Gender { get; set; }
    }

The StakeholderProject model looks like this:

    public class StakeholderProject
    {
        public int StakeholderId { get; set; }
        public virtual Stakeholder Stakeholder { get; set; }

        public int ProjectId { get; set; }
        public virtual Project Project { get; set; }

        public decimal PriorityC { get; set; }

        public decimal PriorityA { get; set; }
}

There is no [Key] attribute in StakeholderProject model because it is compound key defined in OnModelCreating as:

builder.Entity<StakeholderProject>().HasKey(c => new { c.StakeholderId, c.ProjectId });
builder.Entity<StakeholderProject>().HasOne(o => o.Stakeholder).WithMany().OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Restrict);
builder.Entity<StakeholderProject>().HasOne(o => o.Project).WithMany().OnDelete(Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior.Restrict);

If I use OrderBy on Gender property (i.e. "Gender.Name"), then it works normally. The Gender model is:
    public class Gender
    {
        [Key]
        public int GenderId { get; set; }
        public string Name { get; set; }
    }

So, the problem probably lies in the compound key or inability to decorate StakeholderProject model with [Key] attribute twice.

**Comment by StefH** [comment] 2017-09-03 18:05
This can be closed?

**Comment by belmirp** [comment] 2017-09-03 18:36
So, no solution for this? Or it is not planned to work in this way?

**Comment by StefH** [comment] 2017-09-04 05:54
Can you try to rebuild the `dynamic Linq query` into a `normal Linq query` and check if that works with that Key?

**Comment by belmirp** [comment] 2017-09-04 09:22
I've rebuilt it, and it is indeed a problem in something else, because it still doesn't work. Never mind, I will analyze it further myself. You can close this now. And thank you for your patience and assistance.

**Comment by StefH** [comment] 2017-09-04 10:30
OK. I will close for now, if you find a solution, just re-open this issue or create a new one.

**Closed by StefH** 2017-09-04 10:30 UTC
Labels: question
