### ISSUE TITLE
Feature: Support for EF Core 2.0's EF.Functions.Like()

### ISSUE THREAD

**Issue by ascott18** [StefH/System.Linq.Dynamic.Core#105] opened 2017-09-28 18:20 UTC
Are there any plans to support the Like() function from EF Core 2.0? https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-entity-framework-core-2-0/

I'd like to be able to write something like this (contrived example):
```
db.Customers
    .Where("EF.Functions.Like(City, @0)", "L%do%")
```

**Comment by StefH** [comment] 2017-09-30 07:05
I'll take a look.

**Comment by StefH** [comment] 2017-11-15 20:45
No planned date yet.

Do you have a page/code/info from all the supported methods?

**Comment by StefH** [comment] 2017-11-15 21:57
@japerr 
Logic is added, get latest version from github.

See console app `ConsoleAppEF2.0` for details how to use it.

**Comment by mhosman** [comment] 2017-12-02 03:55
Hey @StefH, this is not working for me. In the example you made:  context.Cars.Where("DynamicFunctions.Like(Brand, \"%a%\")"); What's DynamicFunctions? I get an error that is not defined for Cars. Could you please post a basic usage of this? Thank you very much!!

**Comment by mhosman** [comment] 2017-12-02 04:19
Sorry It's working okay. I just forget to add:
`        public static bool Like(string matchExpression, string pattern) => EF.Functions.Like(matchExpression, pattern);`

**Comment by czielin** [comment] 2017-12-23 00:00
Will this work in EF 6? If not is there a way to add a version of the SQL LIKE function that will work with work with wildcards?

I'm trying the following...

queryable.Where("parts.any(DynamicFunctions.Like(subpart.type, @0)) ", "%test");

However, I see this error when trying to execute...

System.Linq.Dynamic.Core.Exceptions.ParseException: 'No property or field 'DynamicFunctions' exists in type 'Part''

**Comment by fchiumeo** [comment] 2018-04-18 18:26
not working

```cs
var j = await UnidadTrabajo
                           .Set<Competidora>()
                           .Where("DynamicFunctions.Like(RazonSocial, \"%a%\")")
                           .ToListAsync();
```

Microsoft.EntityFrameworkCore.Query:Warning: The LINQ expression 'where Like([<generated>_1].RazonSocial, "%a%")' could not be translated and will be evaluated locally.

**Comment by yyjdelete** [comment] 2018-07-28 03:11
One workaround is to add both `Microsoft.EntityFrameworkCore.EF` and `Microsoft.EntityFrameworkCore.DbFunctionsExtensions` as `customTypes` and use it as
`DbFunctionsExtensions.Like(EF.Functions, "matchExpression", "pattern")`

**Comment by StefH** [comment] 2018-07-28 07:10
@fchiumeo Make sure to include the NuGet `Microsoft.EntityFrameworkCore.DynamicLinq` because this functionality is only present in EF Core.

@yyjdelete 
This is already implemented:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/master/src/Microsoft.EntityFrameworkCore.DynamicLinq/DynamicFunctions.cs

**Comment by StefH** [comment] 2018-07-28 07:11
@czielin No support possible for EF 6.

**Comment by yyjdelete** [comment] 2018-07-28 07:38
@StefH 
Yes, it can get the same data, but it's evaluated locally instead of be translated to SQL. You can see the same warn as @fchiumeo described in the log output with `ConsoleApp_netcore2.0_EF2.0.1`(or 2.1), and see no `like` in the output SQL.

**Comment by StefH** [comment] 2018-07-28 13:57
OK. I'm able to reproduce. (Sometimes it seems the console logging is lagging behind or not showing all?)

@yyjdelete Do you have a fix ? Because I tried
``` c#
public static bool Like(string matchExpression, string pattern) => Microsoft.EntityFrameworkCore.DbFunctionsExtensions.Like(EF.Functions, matchExpression, pattern);
```
And that does not work.

**Comment by yyjdelete** [comment] 2018-07-28 14:54
@StefH
I don't have, I just use the extension methods as normal static method directly now.
```cs
            public HashSet<Type> GetCustomTypes()
            {
                    return new HashSet<Type>()
                    {
                        //typeof(SqlServerDbFunctionsExtensions),
                        typeof(DbFunctionsExtensions),
                        typeof(EF),
                    };
            }
var dynamicCarsLike1 = context.Cars.Where(config, "DbFunctionsExtensions.Like(EF.Functions, Brand, \"%a%\")");
```

**Comment by StefH** [comment] 2018-07-29 09:10
In that, the workaround would be just to add these here:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/EF_Functions_Like/src/System.Linq.Dynamic.Core/Parser/PredefinedTypesHelper.cs#L66

This works fine: I did trace the sql commands with sql profiler.

**Comment by mightyvoodoo** [comment] 2018-11-02 18:08
Hello, @StefH, I wanted to ask is any solution here now?
Will be glad for any answers or workarounds... Thanks!

**.NET Core 2.1**

Doing:
```C#
using System.Linq.Dynamic.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.DynamicLinq;
```
```C#
var result = _dbContext.Entry(entry).Collection("related").Query().Where("DynamicFunctions.Like(related, @0)", query);
```

Getting:
> ParseException: No applicable method 'Like' exists in type 'DynamicFunctions'

**Comment by StefH** [comment] 2018-11-02 19:53
I think I still need to update some code which I started at Jul 29, 2018 in branch https://github.com/StefH/System.Linq.Dynamic.Core/tree/EF_Functions_Like

After this weekend I'll take a look if this works.

**Comment by mightyvoodoo** [comment] 2018-11-02 20:29
Thank you for quick response, @StefH 

First exception raised because of my fault.
I figured out some more:
```C#
Where("DynamicFunctions.Like(related, @0)", query);
```
gives
>...could not be translated and will be evaluated locally.

how it was said earlier.

But:
> ... No property or field...

raises now, when calling like you pointed earlier too.

Probably, I must add specified public function to one of my related classes. Will check it later.

\
If you could take a look, it would be great...
:coffee: on me :smiley:

**Comment by anumeetsoni** [comment] 2018-11-15 15:24
> @StefH
> I don't have, I just use the extension methods as normal static method directly now.
> 
> ```cs
>             public HashSet<Type> GetCustomTypes()
>             {
>                     return new HashSet<Type>()
>                     {
>                         //typeof(SqlServerDbFunctionsExtensions),
>                         typeof(DbFunctionsExtensions),
>                         typeof(EF),
>                     };
>             }
> var dynamicCarsLike1 = context.Cars.Where(config, "DbFunctionsExtensions.Like(EF.Functions, Brand, \"%a%\")");
> ```

Hey guys !! Thanks for all your work, I used your method (as stated above) and it worked perfectly, however, the generated SQL is not using parameters, its making a Text SQL and the generated query is not re-using query cache, any ideas ?

**Comment by doxmo** [comment] 2018-12-03 19:49
Hey guys, this is my solution. I hope that will be useful.
  query = query.Where(q => EF.Functions.Like(
                        q.GetType().GetProperty("FieldName").GetValue(q, null).ToString(),
                        "%Pattern%"));

**Comment by webpony2016** [comment] 2019-01-23 01:47
@anumeetsoni  You're right, the solution works well.
@StefH The same question with @anumeetsoni , how to get a parameterized query? The UseParameterizedNamesInDynamicQuery option does not work for this Like case. Thanks.

**Comment by StefH** [comment] 2019-04-18 06:24
@SocVi100 
I'll have to read this issue again, I'm a bit lost on the current status and the exact issue...

**Comment by SocVi100** [comment] 2019-04-22 10:21
@StefH I'll describe my concrete issue just to put you on precedents:

`qry = qry.Where(tipo => EF.Functions.Like(tipo.GetType().GetProperty("FieldOfTheIQueriable").GetValue(tipo, null).ToString(), "%something%"));`

where qry is an IQueriable...

The qry performs with no problems if there's no nulls among the values stored in the "FieldOfTheIQueriable" column, otherwise fails with a NullReferenceException.

**Comment by Bjego** [comment] 2019-05-14 12:25
Your suggesttions work like a charm - even for other providers like devarts EF extentions...

```csharp
public class DynamicLinqProvider : IDynamicLinkCustomTypeProvider
  {
    public HashSet<Type> GetCustomTypes()
    {
      HashSet<Type> types = new HashSet<Type>();
      types.Add(typeof(OracleFunctions));
      return types;
    }

    public Type ResolveType(string typeName)
    {
      throw new NotImplementedException();
    }
  }

```
using the provider:

```csharp
var whereClause = $"OracleFunctions.ToChar(COLUMNNAME, \"FORMAT\", \"NLS_DATE_LANGUAGE='ENGLISH'\")";

return source.Where(new ParsingConfig { CustomTypeProvider = new DynamicLinqProvider() }, whereClause);
```

**Comment by StefH** [comment] 2019-05-14 14:51
Ok. Closing...

**Closed by StefH** 2019-05-14 14:51 UTC
Labels: feature

**Comment by Bjego** [comment] 2019-05-14 15:20
Maybe you could update the Wiki and explain how to add "Dbhelpers" with such a selfwritten IDynamicLinkCustomTypeProvider. Could reduce the number of new issues here 😉

**Comment by hisuwh** [comment] 2021-07-05 16:51
Anyone have any luck getting this to parameterise properly?
